// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUM_Ft9JbCBM7h5epstYaJwc6bPUn9HlQ',
    appId: '1:83025466654:web:055b87cd85f76aadb0250f',
    messagingSenderId: '83025466654',
    projectId: 'test-app-496b2',
    authDomain: 'test-app-496b2.firebaseapp.com',
    storageBucket: 'test-app-496b2.appspot.com',
    measurementId: 'G-NQJE2VBZ7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhKaJdkhZc1KGMeLp-o0kZyC-sGgiRVh0',
    appId: '1:83025466654:android:61897c227b9c513ab0250f',
    messagingSenderId: '83025466654',
    projectId: 'test-app-496b2',
    storageBucket: 'test-app-496b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7PzrePTCzgn6yXa_F1vUXQzAxffID0o',
    appId: '1:83025466654:ios:9899fd3683b7a7dcb0250f',
    messagingSenderId: '83025466654',
    projectId: 'test-app-496b2',
    storageBucket: 'test-app-496b2.appspot.com',
    iosClientId: '83025466654-0gng42qrjvo29f4vlpi142sfjjnvgjp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sepatuShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7PzrePTCzgn6yXa_F1vUXQzAxffID0o',
    appId: '1:83025466654:ios:9899fd3683b7a7dcb0250f',
    messagingSenderId: '83025466654',
    projectId: 'test-app-496b2',
    storageBucket: 'test-app-496b2.appspot.com',
    iosClientId: '83025466654-0gng42qrjvo29f4vlpi142sfjjnvgjp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sepatuShop',
  );
}
